PiWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PiWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PiWeb/Controllers/ProduitMedicauxController.cs
using Exam.Domain.Entities;
using Exam.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PiWeb.Controllers
{
    public class ProduitMedicauxController : Controller
    {
        IProduitMedicaux pdts=new ProduitMedicauxServices();
        IadminService ad = new AdminService();
        // GET: ProduitMedicaux
        public ActionResult Index()
        {
          var t=  pdts.GetAll();
            return View(t);
        }

        // GET: ProduitMedicaux/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProduitMedicaux/Create
        public ActionResult Create()
        {
         var a=   ad.GetAll();
            ViewBag.ad = new SelectList(a, "IDAdmin", "IDAdmin");
            return View();
        }

        // POST: ProduitMedicaux/Create
        [HttpPost]
        public ActionResult Create(Produit_Medicaux pdt)
        {
            pdts.Add(pdt);
            pdts.Commit();
            return RedirectToAction("Index");
        }

        // GET: ProduitMedicaux/Edit/5
        public ActionResult Edit(int id)
        {
            var t = pdts.GetById(id);
            return View(t);
        }

        // POST: ProduitMedicaux/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Produit_Medicaux pdt)
        {
            //pdts.Update(pdt);
            //pdts.Commit();
            //return RedirectToAction("Index");

            //Payment payment = new Payment();
            //pdt = pdts.GetById(id);
            //payment.Status = true;
            ////db.Entry(payment).State = EntityState.Modified;
            ////db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: ProduitMedicaux/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProduitMedicaux/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PiWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PiWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PiWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PiWeb/Views/ProduitMedicaux/Create.cshtml
@model Exam.Domain.Entities.Produit_Medicaux

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produit_Medicaux</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomProduit_Medicaux, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomProduit_Medicaux, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomProduit_Medicaux, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qantite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qantite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qantite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDAdmin", (SelectList)ViewData["ad"])
                @Html.ValidationMessageFor(model => model.IDAdmin)
            </div>
        </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
  
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

PiWeb/Views/ProduitMedicaux/Edit.cshtml
@model Exam.Domain.Entities.Produit_Medicaux

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produit_Medicaux</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDProduit_Medicaux)

        <div class="form-group">
            @Html.LabelFor(model => model.NomProduit_Medicaux, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomProduit_Medicaux, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomProduit_Medicaux, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Qantite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Qantite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Qantite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDAdmin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDAdmin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDAdmin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PiWeb/Views/ProduitMedicaux/Index.cshtml
@model IEnumerable<Exam.Domain.Entities.Produit_Medicaux>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NomProduit_Medicaux)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qantite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IDAdmin)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NomProduit_Medicaux)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Qantite)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Prix)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IDAdmin)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IDProduit_Medicaux }) |
            @Html.ActionLink("Details", "Details", new { id=item.IDProduit_Medicaux }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.IDProduit_Medicaux })
        </td>
    </tr>
}

</table>

PiWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PiWeb/Views/Shared/myLayout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Medicare Template</title>
    @Styles.Render("~/Content/css")
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href=@Url.Content("~/Content/css/animate.css")>
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href=@Url.Content("~/Content/css/icomoon.css")>
    <!-- Bootstrap  -->
    <link rel="stylesheet" href=@Url.Content("~/Content/css/bootstrap.css")>
    <!-- Magnific Popup -->
    <link rel="stylesheet" href=@Url.Content("~/Content/css/magnific-popup.css")>
    <!-- Owl Carousel  -->
    <link rel="stylesheet" href=@Url.Content("~/Content/css/owl.carousel.min.css")>
    <link rel="stylesheet" href=@Url.Content("~/Content/css/owl.theme.default.min.css")>
    <!-- Flexslider  -->
    <link rel="stylesheet" href=@Url.Content("~/Content/css/flexslider.css")>
    <!-- Flaticons  -->
    <link rel="stylesheet" href=@Url.Content("~/Content/fonts/flaticon/font/flaticon.css")>
    <!-- Theme style  -->
    <link rel="stylesheet" href=@Url.Content("~/Content/css/style.css")>
    <!-- Modernizr JS -->
    <script src=@Url.Content("~/Content/js/modernizr-2.6.2.min.js")></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <div class="colorlib-loader"></div>

    <div id="page">
        <nav class="colorlib-nav" role="navigation">
            <div class="top-menu">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="top">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div id="colorlib-logo"><a href="index.html"><i class="flaticon-stethoscope"></i>Medi<span>care</span></a></div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="num">
                                            <span class="icon"><i class="icon-phone"></i></span>
                                            <p><a href="#">111-222-333</a><br><a href="#">99-222-333</a></p>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="loc">
                                            <span class="icon"><i class="icon-location"></i></span>
                                            <p><a href="#">88 Route West 21th Street, Suite 721 New York NY 10016</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="menu-wrap">
                    <div class="container">
                        <div class="row">
                            <div class="col-xs-8">
                                <div class="menu-1">
                                    <ul>
                                        <li class="active"><a href="index.html">Home</a></li>
                                        <li class="has-dropdown">
                                            @Html.ActionLink("Produit Medicaux", "Index", "ProduitMedicaux")
                                            <ul class="dropdown">
                                                <li><a href="doctors-single.html">Single Doctor</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="services.html">RDV</a></li>
                                        <li class="has-dropdown">
                                            <a href="departments.html">Formations</a>
                                            <ul class="dropdown">
                                                <li><a href="departments-single.html">Plasetic Surgery Department</a></li>
                                                <li><a href="departments-single.html">Dental Department</a></li>
                                                <li><a href="departments-single.html">Psychological Department</a></li>
                                            </ul>
                                        </li>
                                        <li class="has-dropdown">
                                            <a href="blog.html">Document</a>
                                            <ul class="dropdown">
                                                <li><a href="blog-single.html">Single Blog</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="contact.html">Contact</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <p class="btn-cta"><a href="appointment.html"><span>Make an Appointment <i class="icon-calendar3"></i></span></a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container">
        @RenderBody()
        </div>
       

        <footer id="colorlib-footer" role="contentinfo">
            <div class="overlay"></div>
            <div class="container">
                <div class="row row-pb-md">
                    <div class="col-md-3 colorlib-widget">
                        <h3>Medicare</h3>
                        <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    </div>
                    <div class="col-md-3 col-md-push-1 colorlib-widget">
                        <h3>Navigation</h3>
                        <ul class="colorlib-footer-links">
                            <li><a href="#"><i class="icon-check"></i> Department</a></li>
                            <li><a href="#"><i class="icon-check"></i> Blog</a></li>
                            <li><a href="#"><i class="icon-check"></i> Contact</a></li>
                            <li><a href="#"><i class="icon-check"></i> Terms</a></li>
                            <li><a href="#"><i class="icon-check"></i> Shop</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 colorlib-widget">
                        <h3>Our Services</h3>
                        <ul class="colorlib-footer-links">
                            <li><a href="#"><i class="icon-check"></i> Heart Surgery</a></li>
                            <li><a href="#"><i class="icon-check"></i> Surgical Treatment</a></li>
                            <li><a href="#"><i class="icon-check"></i> General Treatment</a></li>
                            <li><a href="#"><i class="icon-check"></i> Medical Treatment</a></li>
                            <li><a href="#"><i class="icon-check"></i> Help Desk</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 colorlib-widget">
                        <h3>Make an Appointment</h3>
                        <form class="contact-form">
                            <div class="form-group">
                                <label for="name" class="sr-only">Name</label>
                                <input type="name" class="form-control" id="name" placeholder="Name">
                            </div>
                            <div class="form-group">
                                <label for="email" class="sr-only">Email</label>
                                <input type="email" class="form-control" id="email" placeholder="Email">
                            </div>
                            <div class="form-group">
                                <label for="message" class="sr-only">Message</label>
                                <textarea class="form-control" id="message" rows="3" placeholder="Message"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" id="btn-submit" class="btn btn-primary btn-send-message btn-md" value="Send Message">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row copyright">
                <div class="col-md-12 text-center">
                    <p>
                        <small class="block">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </small>
                        <small class="block">Demo Images: <a href="http://unsplash.co/" target="_blank">Unsplash</a> , <a href="https://www.pexels.com/" target="_blank">Pexels</a></small>
                    </p>
                </div>
            </div>
        </footer>
    </div>
    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>

    <!-- jQuery -->

    <script src=@Url.Content("~/Content/js/jquery.min.js")></script>
    <!-- jQuery Easing -->
    <script src=@Url.Content("~/Content/js/jquery.easing.1.3.js")></script>
    <!-- Bootstrap -->
    <script src=@Url.Content("~/Content/js/bootstrap.min.js")></script>
    <!-- Waypoints -->
    <script src=@Url.Content("~/Content/js/jquery.waypoints.min.js")></script>
    <!-- Stellar Parallax -->
    <script src=@Url.Content("~/Content/js/jquery.stellar.min.js")></script>
    <!-- Carousel -->
    <script src=@Url.Content("~/Content/js/owl.carousel.min.js")></script>
    <!-- Flexslider -->
    <script src=@Url.Content("~/Content/js/jquery.flexslider-min.js")></script>
    <!-- countTo -->
    <script src=@Url.Content("~/Content/js/jquery.countTo.js")></script>
    <!-- Magnific Popup -->
    <script src=@Url.Content("~/Content/js/jquery.magnific-popup.min.js")></script>
    <script src=@Url.Content("~/Content/js/magnific-popup-options.js")></script>
    <!-- Sticky Kit -->
    <script src=@Url.Content("~/Content/js/sticky-kit.min.js")></script>
    <!-- Main -->
    <script src=@Url.Content("~/Content/js/main.js")></script>
</body>
</html>